import type { ZodTypeAny } from 'zod';

import { delegateSchemas } from '../delegate/routes';
import { focusSchemas } from '../focus/routes';
import { intelligenceSchemas } from '../intelligence/routes';
import { ledgerSchemas } from '../ledger/routes';
import { policySchemas } from '../policy/routes';
import { scenarioSchemas } from '../scenario/routes';
import { workflowSchemas } from '../workflow/routes';

export type RpcRegistryEntry = {
  service: string;
  rpc: string;
  method: 'GET' | 'POST';
  path: string;
  requiresEnvelope: boolean;
  requestSchema?: ZodTypeAny;
};

export const rpcRegistry: RpcRegistryEntry[] = [
  {
    service: 'ledger.v1',
    rpc: 'SubmitCommand',
    method: 'POST',
    path: '/ledger/v1/submit-command',
    requiresEnvelope: true,
    requestSchema: ledgerSchemas.submitCommand,
  },
  {
    service: 'ledger.v1',
    rpc: 'StreamEvents',
    method: 'POST',
    path: '/ledger/v1/stream-events',
    requiresEnvelope: false,
    requestSchema: ledgerSchemas.streamEvents,
  },
  {
    service: 'ledger.v1',
    rpc: 'GetProjectionSnapshot',
    method: 'POST',
    path: '/ledger/v1/projection-snapshot',
    requiresEnvelope: false,
    requestSchema: ledgerSchemas.projectionSnapshot,
  },
  {
    service: 'workflow.v1',
    rpc: 'ResolveNextAction',
    method: 'POST',
    path: '/workflow/v1/resolve-next-action',
    requiresEnvelope: true,
    requestSchema: workflowSchemas.resolveNextAction,
  },
  {
    service: 'workflow.v1',
    rpc: 'RunPlaybook',
    method: 'POST',
    path: '/workflow/v1/run-playbook',
    requiresEnvelope: true,
    requestSchema: workflowSchemas.runPlaybook,
  },
  {
    service: 'workflow.v1',
    rpc: 'ReplayPlaybookRun',
    method: 'POST',
    path: '/workflow/v1/replay-playbook-run',
    requiresEnvelope: true,
    requestSchema: workflowSchemas.replayPlaybookRun,
  },
  {
    service: 'workflow.v1',
    rpc: 'ListPlaybookRuns',
    method: 'POST',
    path: '/workflow/v1/list-playbook-runs',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.listPlaybookRuns,
  },
  {
    service: 'workflow.v1',
    rpc: 'GetMoneyPulse',
    method: 'GET',
    path: '/workflow/v1/money-pulse',
    requiresEnvelope: false,
  },
  {
    service: 'workflow.v1',
    rpc: 'GetRuntimeMetrics',
    method: 'GET',
    path: '/workflow/v1/runtime-metrics',
    requiresEnvelope: false,
  },
  {
    service: 'workflow.v1',
    rpc: 'GetOpsActivityPipelineStatus',
    method: 'GET',
    path: '/workflow/v1/ops-activity-pipeline-status',
    requiresEnvelope: false,
  },
  {
    service: 'workflow.v1',
    rpc: 'GetNarrativePulse',
    method: 'POST',
    path: '/workflow/v1/get-narrative-pulse',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.getNarrativePulse,
  },
  {
    service: 'workflow.v1',
    rpc: 'ListCloseRuns',
    method: 'POST',
    path: '/workflow/v1/list-close-runs',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.listCloseRuns,
  },
  {
    service: 'workflow.v1',
    rpc: 'RunCloseRoutine',
    method: 'POST',
    path: '/workflow/v1/run-close-routine',
    requiresEnvelope: true,
    requestSchema: workflowSchemas.runCloseRoutine,
  },
  {
    service: 'workflow.v1',
    rpc: 'ApplyBatchPolicy',
    method: 'POST',
    path: '/workflow/v1/apply-batch-policy',
    requiresEnvelope: true,
    requestSchema: workflowSchemas.applyBatchPolicy,
  },
  {
    service: 'workflow.v1',
    rpc: 'ExecuteChain',
    method: 'POST',
    path: '/workflow/v1/execute-chain',
    requiresEnvelope: true,
    requestSchema: workflowSchemas.executeChain,
  },
  {
    service: 'workflow.v1',
    rpc: 'RollbackPlaybookRun',
    method: 'POST',
    path: '/workflow/v1/rollback-playbook-run',
    requiresEnvelope: true,
    requestSchema: workflowSchemas.rollbackPlaybookRun,
  },
  {
    service: 'workflow.v1',
    rpc: 'RollbackCommandRun',
    method: 'POST',
    path: '/workflow/v1/rollback-command-run',
    requiresEnvelope: true,
    requestSchema: workflowSchemas.rollbackCommandRun,
  },
  {
    service: 'workflow.v1',
    rpc: 'ListCommandRuns',
    method: 'POST',
    path: '/workflow/v1/list-command-runs',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.listCommandRuns,
  },
  {
    service: 'workflow.v1',
    rpc: 'ListCommandRunsByIds',
    method: 'POST',
    path: '/workflow/v1/list-command-runs-by-ids',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.listCommandRunsByIds,
  },
  {
    service: 'workflow.v1',
    rpc: 'ListOpsActivity',
    method: 'POST',
    path: '/workflow/v1/list-ops-activity',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.listOpsActivity,
  },
  {
    service: 'workflow.v1',
    rpc: 'BackfillOpsActivity',
    method: 'POST',
    path: '/workflow/v1/backfill-ops-activity',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.backfillOpsActivity,
  },
  {
    service: 'workflow.v1',
    rpc: 'RunOpsActivityMaintenance',
    method: 'POST',
    path: '/workflow/v1/run-ops-activity-maintenance',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.runOpsActivityMaintenance,
  },
  {
    service: 'workflow.v1',
    rpc: 'StartOpsActivityPipeline',
    method: 'POST',
    path: '/workflow/v1/start-ops-activity-pipeline',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.startOpsActivityPipeline,
  },
  {
    service: 'workflow.v1',
    rpc: 'ClaimQueueJobs',
    method: 'POST',
    path: '/workflow/v1/claim-queue-jobs',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.claimQueueJobs,
  },
  {
    service: 'workflow.v1',
    rpc: 'ClaimWorkerJobFingerprint',
    method: 'POST',
    path: '/workflow/v1/claim-worker-job-fingerprint',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.claimWorkerJobFingerprint,
  },
  {
    service: 'workflow.v1',
    rpc: 'AckQueueJob',
    method: 'POST',
    path: '/workflow/v1/ack-queue-job',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.ackQueueJob,
  },
  {
    service: 'workflow.v1',
    rpc: 'CheckWorkerJobFingerprint',
    method: 'POST',
    path: '/workflow/v1/check-worker-job-fingerprint',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.checkWorkerJobFingerprint,
  },
  {
    service: 'workflow.v1',
    rpc: 'RequeueExpiredQueueJobs',
    method: 'POST',
    path: '/workflow/v1/requeue-expired-queue-jobs',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.requeueExpiredQueueJobs,
  },
  {
    service: 'workflow.v1',
    rpc: 'ListWorkerDeadLetters',
    method: 'POST',
    path: '/workflow/v1/list-worker-dead-letters',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.listWorkerDeadLetters,
  },
  {
    service: 'workflow.v1',
    rpc: 'ReplayWorkerDeadLetters',
    method: 'POST',
    path: '/workflow/v1/replay-worker-dead-letters',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.replayWorkerDeadLetters,
  },
  {
    service: 'workflow.v1',
    rpc: 'ResolveWorkerDeadLetter',
    method: 'POST',
    path: '/workflow/v1/resolve-worker-dead-letter',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.resolveWorkerDeadLetter,
  },
  {
    service: 'workflow.v1',
    rpc: 'ReopenWorkerDeadLetter',
    method: 'POST',
    path: '/workflow/v1/reopen-worker-dead-letter',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.reopenWorkerDeadLetter,
  },
  {
    service: 'workflow.v1',
    rpc: 'GetWorkerQueueHealth',
    method: 'POST',
    path: '/workflow/v1/worker-queue-health',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.workerQueueHealth,
  },
  {
    service: 'workflow.v1',
    rpc: 'AcquireWorkerQueueLease',
    method: 'POST',
    path: '/workflow/v1/acquire-worker-queue-lease',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.acquireWorkerQueueLease,
  },
  {
    service: 'workflow.v1',
    rpc: 'ReleaseWorkerQueueLease',
    method: 'POST',
    path: '/workflow/v1/release-worker-queue-lease',
    requiresEnvelope: false,
    requestSchema: workflowSchemas.releaseWorkerQueueLease,
  },
  {
    service: 'scenario.v1',
    rpc: 'CreateBranch',
    method: 'POST',
    path: '/scenario/v1/create-branch',
    requiresEnvelope: true,
    requestSchema: scenarioSchemas.createBranch,
  },
  {
    service: 'scenario.v1',
    rpc: 'ApplyMutation',
    method: 'POST',
    path: '/scenario/v1/apply-mutation',
    requiresEnvelope: true,
    requestSchema: scenarioSchemas.applyMutation,
  },
  {
    service: 'scenario.v1',
    rpc: 'SimulateBranch',
    method: 'POST',
    path: '/scenario/v1/simulate-branch',
    requiresEnvelope: true,
    requestSchema: scenarioSchemas.simulateBranch,
  },
  {
    service: 'scenario.v1',
    rpc: 'PromoteBranchRun',
    method: 'POST',
    path: '/scenario/v1/promote-branch-run',
    requiresEnvelope: true,
    requestSchema: scenarioSchemas.promoteBranchRun,
  },
  {
    service: 'scenario.v1',
    rpc: 'CompareOutcomes',
    method: 'POST',
    path: '/scenario/v1/compare-outcomes',
    requiresEnvelope: false,
    requestSchema: scenarioSchemas.compareOutcomes,
  },
  {
    service: 'scenario.v1',
    rpc: 'AdoptionCheck',
    method: 'POST',
    path: '/scenario/v1/adoption-check',
    requiresEnvelope: false,
    requestSchema: scenarioSchemas.adoptionCheck,
  },
  {
    service: 'scenario.v1',
    rpc: 'ListMutations',
    method: 'POST',
    path: '/scenario/v1/list-mutations',
    requiresEnvelope: false,
    requestSchema: scenarioSchemas.listMutations,
  },
  {
    service: 'scenario.v1',
    rpc: 'GetLineage',
    method: 'POST',
    path: '/scenario/v1/lineage',
    requiresEnvelope: false,
    requestSchema: scenarioSchemas.lineage,
  },
  {
    service: 'scenario.v1',
    rpc: 'AdoptBranch',
    method: 'POST',
    path: '/scenario/v1/adopt-branch',
    requiresEnvelope: true,
    requestSchema: scenarioSchemas.adoptBranch,
  },
  {
    service: 'focus.v1',
    rpc: 'GetAdaptivePanel',
    method: 'GET',
    path: '/focus/v1/adaptive-panel',
    requiresEnvelope: false,
  },
  {
    service: 'focus.v1',
    rpc: 'ListActionOutcomes',
    method: 'POST',
    path: '/focus/v1/list-action-outcomes',
    requiresEnvelope: false,
    requestSchema: focusSchemas.listActionOutcomes,
  },
  {
    service: 'focus.v1',
    rpc: 'RecordActionOutcome',
    method: 'POST',
    path: '/focus/v1/record-action-outcome',
    requiresEnvelope: true,
    requestSchema: focusSchemas.recordActionOutcome,
  },
  {
    service: 'delegate.v1',
    rpc: 'ListLanes',
    method: 'POST',
    path: '/delegate/v1/list-lanes',
    requiresEnvelope: false,
    requestSchema: delegateSchemas.listLanes,
  },
  {
    service: 'delegate.v1',
    rpc: 'ListLaneEvents',
    method: 'POST',
    path: '/delegate/v1/list-lane-events',
    requiresEnvelope: false,
    requestSchema: delegateSchemas.listLaneEvents,
  },
  {
    service: 'delegate.v1',
    rpc: 'AssignLane',
    method: 'POST',
    path: '/delegate/v1/assign-lane',
    requiresEnvelope: true,
    requestSchema: delegateSchemas.assignLane,
  },
  {
    service: 'delegate.v1',
    rpc: 'AcceptLane',
    method: 'POST',
    path: '/delegate/v1/accept-lane',
    requiresEnvelope: true,
    requestSchema: delegateSchemas.transitionLane,
  },
  {
    service: 'delegate.v1',
    rpc: 'CompleteLane',
    method: 'POST',
    path: '/delegate/v1/complete-lane',
    requiresEnvelope: true,
    requestSchema: delegateSchemas.transitionLane,
  },
  {
    service: 'delegate.v1',
    rpc: 'RejectLane',
    method: 'POST',
    path: '/delegate/v1/reject-lane',
    requiresEnvelope: true,
    requestSchema: delegateSchemas.transitionLane,
  },
  {
    service: 'delegate.v1',
    rpc: 'ReopenLane',
    method: 'POST',
    path: '/delegate/v1/reopen-lane',
    requiresEnvelope: true,
    requestSchema: delegateSchemas.transitionLane,
  },
  {
    service: 'delegate.v1',
    rpc: 'CommentLane',
    method: 'POST',
    path: '/delegate/v1/comment-lane',
    requiresEnvelope: true,
    requestSchema: delegateSchemas.commentLane,
  },
  {
    service: 'policy.v1',
    rpc: 'GetEgressPolicy',
    method: 'GET',
    path: '/policy/v1/egress-policy',
    requiresEnvelope: false,
  },
  {
    service: 'policy.v1',
    rpc: 'SetEgressPolicy',
    method: 'POST',
    path: '/policy/v1/set-egress-policy',
    requiresEnvelope: true,
    requestSchema: policySchemas.setEgressPolicy,
  },
  {
    service: 'policy.v1',
    rpc: 'ListEgressAudit',
    method: 'POST',
    path: '/policy/v1/list-egress-audit',
    requiresEnvelope: false,
    requestSchema: policySchemas.listEgressAudit,
  },
  {
    service: 'intelligence.v1',
    rpc: 'Recommend',
    method: 'POST',
    path: '/intelligence/v1/recommend',
    requiresEnvelope: true,
    requestSchema: intelligenceSchemas.recommend,
  },
  {
    service: 'intelligence.v1',
    rpc: 'Explain',
    method: 'POST',
    path: '/intelligence/v1/explain',
    requiresEnvelope: true,
    requestSchema: intelligenceSchemas.explain,
  },
  {
    service: 'intelligence.v1',
    rpc: 'Classify',
    method: 'POST',
    path: '/intelligence/v1/classify',
    requiresEnvelope: true,
    requestSchema: intelligenceSchemas.classify,
  },
  {
    service: 'intelligence.v1',
    rpc: 'Forecast',
    method: 'POST',
    path: '/intelligence/v1/forecast',
    requiresEnvelope: true,
    requestSchema: intelligenceSchemas.forecast,
  },
  {
    service: 'intelligence.v1',
    rpc: 'LearnCorrection',
    method: 'POST',
    path: '/intelligence/v1/learn-correction',
    requiresEnvelope: true,
    requestSchema: intelligenceSchemas.learnCorrection,
  },
];

export function findRpcRegistryEntry(service: string, rpc: string): RpcRegistryEntry | undefined {
  return rpcRegistry.find(entry => entry.service === service && entry.rpc === rpc);
}
